### ISSUE TITLE
\NewCommandCopy with \endminipage

### ISSUE THREAD

**Issue by bdtc** [josephwright/etoolbox#41] opened 2021-12-20 10:21 UTC
```
\documentclass{article}

\usepackage{etoolbox}

\NewCommandCopy{\mytest}{\endminipage}

\begin{document}
Some text.
\end{document}
```
`! Paragraph ended before \etb@carsquare was complete.`

The above works fine without etoolbox.

The above also works fine with etoolbox and most other environments.

**Comment by muzimuzhi** [comment] 2021-12-20 16:07
A mis-spelling in issue title: `\NewCopyCommand` should be `\NewCommandCopy`.

**Comment by muzimuzhi** [comment] 2021-12-20 16:25
Duplicate of #35. Already fixed but not released yet.

btw There's a mis-spelling in issue title: `\NewCopyCommand` should be `\NewCommandCopy`.

**Comment by bdtc** [comment] 2021-12-21 11:48
Edited the title.

**Closed as completed** 2022-01-04 11:02 UTC
